version: "3.9"

services:
  inference_service:
    build: ./services/inference_service
    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - inference_service

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus